import type { SuitableFor } from "./ride-types.js";
import type { RideVehicle } from "./ride-types.js";
import { DEFAULT_VEHICLE_PRICING } from "../../shared/ride/vehicle-pricing.js";

const pricingFor = (
  overrides?: Partial<typeof DEFAULT_VEHICLE_PRICING>,
) => ({ ...DEFAULT_VEHICLE_PRICING, ...overrides });

/** Seed fleet when collection is empty — mirrors customer mock catalog. */
export const SEED_VEHICLES: Omit<RideVehicle, "_id" | "createdAt" | "updatedAt">[] =
  [
    {
      id: "v-vios",
      name: "Toyota Vios",
      brand: "Toyota",
      model: "Vios",
      licensePlate: "",
      seats: 4,
      transmission: "Số tự động",
      fuel: "Xăng",
      images: [
        "https://www.toyota.com.vn/compression/webp?u=%2FResources%2FVehicles%2F318%2F531%2Flibrary%2Facc3306c8126347f9bd25a71dbffbaaf-f964cab1c8.png%3Fv%3D445b75d633&q=80",
      ],
      features: ["Điều hòa", "Camera lùi", "Xe riêng + tài xế"],
      suitableFor: ["airport", "business", "medical", "travel"] as SuitableFor[],
      pricing: pricingFor({
        fuelType: "Xăng",
        fuelConsumptionPer100Km: 7,
        baseFare: 180_000,
        pricePerKm: 11_000,
        dailyRate: 1_200_000,
      }),
      active: true,
      status: "AVAILABLE",
    },
    {
      id: "v-accent",
      name: "Hyundai Accent",
      brand: "Hyundai",
      model: "Accent",
      licensePlate: "",
      seats: 5,
      transmission: "Số tự động",
      fuel: "Xăng",
      images: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSc1mGghuTsJUYPP8GLA_hUWvixjvpAAOuFpeWk_XvR8w&s=10",
      ],
      features: ["Điều hòa", "Màn hình giải trí", "Xe riêng + tài xế"],
      suitableFor: [
        "airport",
        "business",
        "medical",
        "travel",
        "family",
      ] as SuitableFor[],
      pricing: pricingFor({
        fuelType: "Xăng",
        fuelConsumptionPer100Km: 7.5,
        baseFare: 190_000,
        dailyRate: 1_300_000,
      }),
      active: true,
      status: "AVAILABLE",
    },
    {
      id: "v-fortuner",
      name: "Toyota Fortuner Legender",
      brand: "Toyota",
      model: "Fortuner Legender",
      licensePlate: "",
      seats: 7,
      transmission: "Số tự động",
      fuel: "Máy dầu",
      images: [
        "https://cdn.dailyxe.com.vn/image/toyota-fortuner-legender-24-at-4x2-340460j.jpg",
      ],
      features: [
        "Không gian rộng",
        "Điều hòa 2 vùng",
        "Xe riêng + tài xế",
        "Phù hợp hành lý nhiều",
      ],
      suitableFor: [
        "travel",
        "pilgrimage",
        "medical",
        "business",
        "family",
        "airport",
      ] as SuitableFor[],
      pricing: pricingFor({
        fuelType: "Máy dầu",
        fuelConsumptionPer100Km: 9,
        fuelPricePerLiter: 21_000,
        baseFare: 280_000,
        pricePerKm: 15_000,
        dailyRate: 2_000_000,
        includedKm: 250,
      }),
      active: true,
      status: "AVAILABLE",
    },
    {
      id: "v-innova",
      name: "Toyota Innova",
      brand: "Toyota",
      model: "Innova",
      licensePlate: "",
      seats: 7,
      transmission: "Số tự động",
      fuel: "Xăng",
      images: [
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsmt1syR5ilvy1y3HGPHL7Sn_z-tot4x0vVN0jTNNbWA&s=10",
      ],
      features: ["Ghế linh hoạt", "Điều hòa", "Xe riêng + tài xế"],
      suitableFor: [
        "travel",
        "pilgrimage",
        "family",
        "medical",
        "custom",
      ] as SuitableFor[],
      pricing: pricingFor({
        fuelType: "Xăng",
        fuelConsumptionPer100Km: 9,
        baseFare: 250_000,
        pricePerKm: 14_000,
        dailyRate: 1_800_000,
      }),
      active: true,
      status: "AVAILABLE",
    },
    {
      id: "v-transit",
      name: "Ford Transit",
      brand: "Ford",
      model: "Transit",
      licensePlate: "",
      seats: 16,
      transmission: "Số sàn",
      fuel: "Máy dầu",
      images: [],
      features: ["Đoàn lớn", "Hành lý nhiều", "Xe riêng + tài xế"],
      suitableFor: ["pilgrimage", "travel", "custom", "family"] as SuitableFor[],
      pricing: pricingFor({
        fuelType: "Máy dầu",
        fuelConsumptionPer100Km: 12,
        fuelPricePerLiter: 21_000,
        driverRate: 200_000,
        baseFare: 400_000,
        pricePerKm: 18_000,
        dailyRate: 2_800_000,
        includedKm: 250,
        extraKmRate: 12_000,
      }),
      active: true,
      status: "AVAILABLE",
    },
  ];
